export const CART_ADD_HANDLE='CART_ADD_HANDLE';
export const CART_REMOVE_HANDLE='CART_REMOVE_HANDLE'
export const CART_SHIPPING_ADDRESS_SAVE="CART_SHIPPING_ADDRESS_SAVE"
export const CART_PAYMENT_METHOD_SAVE='CART_PAYMENT_METHOD_SAVE'
export const CART_EMPTY='CART_EMPTY'