export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'
export const USER_REGISTER_SUCESS='USER_REGISTER_SUCESS'

export const USER_SIGNIN_START='USER_SIGNIN_START'
export const USER_SIGNIN_FAIL='USER_SIGNIN_FAIL'
export const USER_SIGNIN_SUCESS='USER_SIGNIN_SUCESS'
export const USER_SIGNOUT='USER_SIGNOUT'


export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';